### ISSUE TITLE
Feature requests: changing the order of the highlights/notes and adding highlights/notes incrementally

### ISSUE THREAD

**Issue by TookiTheGreat** [TfTHacker/craft42-readwise#5]
Hi,

First of all: great work with this extension. It is a big help in my move from Obsidian (powerful but ugly) to Craft (beautiful but a bit lacking in power features).

What would make your extension perfect for me would be:
1) Have an option to insert the highlights/notes in the order they appear in the source text, instead of in the order they were entered. The notes I take often serve as a kind of summary for me, so - when reading back my notes - it's easier if the notes follow the order of the book's story. If that's too complicated, a simple 'reverse order' option would work for me in 80% of cases.
2) It's great to have all my highlights/notes in a single place. But I often go back to a book and discover new things to highlight or comment on. It would be great if there is an option to only copy the highlights/notes that are new since the last copy operation. That would let me build up a book page with incremental highlights/notes that grow in batches over time.

I hope that makes sense.

Thanks again for a very useful extension,

Bard

**Comment by TfTHacker** [comment]
In the v4 update now available in “releases”, it sorts the highlights in date order taken. So if you read in order, they will appear this way :-)

Also they now show the date they were taken. So this will help you see what is new. Unfortunately the API for craft is still to weak to really get to more dynamic.

**Comment by TookiTheGreat** [comment]
Thanks. This is already a big improvement.
